### ISSUE TITLE
Application opening edge dev instead of edge stable?

### ISSUE THREAD

**Issue by bobsage123** [gexgd0419/EdgeWindowTabManagerBlock#2]
Was opening stable for me for a while, then after a reboot today it will only open edge dev.

**Comment by gexgd0419** [comment]
This program reads Edge's path from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe`. Edge dev installer will change it to Edge dev's path. After that, if you enter `msedge.exe` in the Run dialog (Win+R), Edge dev will be launched.

I'm only using the stable version, so I didn't find this problem.

**Comment by bobsage123** [comment]
Updating that to stable fixed it, thanks.

**Comment by bobsage123** [comment]
It looks like this is reverting to putting the dev path in that key every time edge updates. Is it possible for a more permanent way to fix this? Thanks

**Comment by gexgd0419** [comment]
I've uploaded a new release version, which allows you to choose a Microsoft Edge version to launch when you have multiple versions installed. It will show a dialog to let you choose a version (Stable, Beta, Dev, etc.) and will remember the choice until you install a new different version. You can also hold CTRL while starting the program to make the version selection dialog show again.

**Comment by bobsage123** [comment]
Awesome, thank you!
