### ISSUE TITLE
The flag to disable tab-manager is back.

### ISSUE THREAD

**Issue by solarflows** [gexgd0419/EdgeWindowTabManagerBlock#3]
[#edge-window-tab-manager](edge://flags/#edge-window-tab-manager) is back in edge 120.0.2210.61 stable release.
![image](https://github.com/gexgd0419/EdgeWindowTabManagerBlock/assets/57535444/6eed73b3-b83e-465d-a4ac-15e2b41f2719)
![image](https://github.com/gexgd0419/EdgeWindowTabManagerBlock/assets/57535444/1760e0b1-b8a1-4b46-9f5b-5c1b779c6259)

**Comment by gexgd0419** [comment]
Updated to 120.0.2210.61. Confirmed that this works.

**Comment by solarflows** [comment]
Good Job

**Comment by spaceemotion** [comment]
I'm on `Version 123.0.2420.53 (Official build) (64-bit)` and the flag seems to have been removed again.
