### ISSUE TITLE
[Q] Way to pass arguments when using this app?

### ISSUE THREAD

**Issue by bobsage123** [gexgd0419/EdgeWindowTabManagerBlock#5]
For example, before I used this app, I would add "--enable-features=GlobalMediaControls" to my edge shortcuts to add these feature in.

Is it possible to do while using this app?

**Comment by gexgd0419** [comment]
Yes, it should be possible.

> You can also pass a path to a certain msedge.exe file as the first command line argument to the program, and the program will launch the specified msedge.exe. Other command line arguments will be passed as-is to the launched Microsoft Edge process.

If the first command line argument is not a path to msedge.exe, all command line arguments will be passed to Edge.

So you can just replace the msedge path in the shortcut target with the path to this program, and leave the other arguments unchanged.

Or if you want to open a certain version of Edge (e.g. Beta), add its path between the path to this program and the rest of the arguments.
