### ISSUE TITLE
It might be possible to use the Image File Execution Options to start this program when Edge is launched.

### ISSUE THREAD

**Issue by hwf1324** [gexgd0419/EdgeWindowTabManagerBlock#6]
我在《Windows Sysinternals 实战指南》中看到了这种方式：

> Image File Execution Options (IFEO)　该注册表位置的子键（及64位版本Windows中对应的子键）主要用于实现大量内部的非公开用途。IFEO子键的公开用途之一是用于设置在运行某一特定应用程序时自动运行另一个备用程序。通过以原始程序的文件名为名创建子键，并在该键中通过“Debugger”值指定备用程序的可执行文件路径，即可以备用程序取代原始程序，并通过自己的命令行环境接受原始程序的路径和命令行参数。这一机制原本是用于以备用程序作为调试器，对调试器启动的新进程进行调试，而非在原程序已经开始运行并加载了所有相关代码之后将调试器附加至进程。然而该机制并不强制要求备用程序必须是调试器，也不会对传递的命令行参数进行检查。实际上Process Explorer（本书第3章介绍过）正是通过这种方式替换任务管理器的。

**Comment by gexgd0419** [comment]
感谢！

实际上起初我就考虑过IFEO调试器的方案，不过遇到了一个问题：Edge是多进程的架构。除了用户启动一个主Edge进程外，主Edge进程还会启动子Edge进程，而IFEO调试器设置会打断子进程的启动流程。所以当时我简单地试了几次，无果，就去研究其他方案了。

不过我最近研究之后反应过来了：既然这个项目本身就是注入Edge进程去hook API函数的，那直接把创建子进程的API也hook了，就可以控制子进程的创建，进而让Edge的子进程能够绕开IFEO调试器。

目前尚不清楚这种实现有没有副作用。测试完成后，计划发布一个新版本。

**Comment by hwf1324** [comment]
好的。

我对系统底层没什么研究，之前因为edge开近两千个标签页总是让资源管理器崩溃，后来就转战Firefox了。可惜当时没有发现这个项目，之后有机会测试一下新版本。

**Comment by gexgd0419** [comment]
新版本已发布。
